version: '3.7'

volumes:
  postgres:

services:
  postgres:
    container_name: postgres_dwh
    image: "postgres:12"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgres/data
    ports:
      - "15432:5432"
